apiVersion: webapp.int128.github.io/v1
kind: Guestbook
metadata:
  labels:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/instance: guestbook-sample
    app.kubernetes.io/part-of: hello-kubebuilder
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: hello-kubebuilder
  name: guestbook-sample
spec:
  # TODO(user): Add fields here
